In [1]:
import numpy

In [3]:
n=numpy.arange(27)

In [12]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [14]:
import cv2

In [20]:
pic = cv2.imread("smallgray.png", 0)

In [21]:
pic

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [23]:
cv2.imwrite("newsmallgrey.png", pic)

True

In [28]:
pic[2,4]

182

In [29]:
for i in pic:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [31]:
print(pic.flat)

In [33]:
pic2=numpy.hstack([pic,pic])

In [34]:
pic2

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [45]:
lst1=numpy.vsplit(pic2, 3)

In [46]:
lst1

[array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147, 198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)]

In [40]:
a1 = lst1[0]

In [41]:
a1

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [42]:
print(a1)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [43]:
for a in a1:
    print(a)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [44]:
for a in a1.flat:
    print(a)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182
